/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface LogoProps {
  isDarkMode: boolean;
}

const Logo: React.FC<LogoProps> = ({ isDarkMode }) => {
  return (
    <div className="flex gap-3 self-start mt-1.5">
      <div className="flex gap-0.5">
        <div
          className={`flex shrink-0 w-4 ${
            isDarkMode ? "bg-indigo-400" : "bg-indigo-600"
          } rounded-none fill-current h-[37px]`}
        />
        <div className="flex flex-col">
          <div
            className={`flex shrink-0 ${
              isDarkMode ? "bg-sky-300" : "bg-sky-400"
            } fill-current h-[17px] rounded-[59px]`}
          />
          <div
            className={`flex shrink-0 ${
              isDarkMode ? "bg-purple-400" : "bg-purple-600"
            } fill-current h-[17px] rounded-[59px]`}
          />
        </div>
      </div>
      <h1
        className={`my-auto text-3xl font-bold leading-none ${
          isDarkMode ? "text-white" : "text-indigo-950"
        }`}
      >
        Logo
      </h1>
    </div>
  );
};

export default Logo;
