/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

interface MobileMenuButtonProps {
  isOpen: boolean;
  toggleMenu: () => void;
  isDarkMode: boolean;
}

const MobileMenuButton: React.FC<MobileMenuButtonProps> = ({
  isOpen,
  toggleMenu,
  isDarkMode,
}) => {
  const lineVariants = {
    closed: { rotate: 0, y: 0 },
    open: (custom: number) => ({
      rotate: custom === 1 ? 45 : custom === 3 ? -45 : 0,
      y: custom === 1 ? 6 : custom === 3 ? -6 : 0,
    }),
  };

  return (
    <button
      className={`md:hidden focus:outline-none ${
        isDarkMode ? "text-white" : "text-gray-800"
      }`}
      onClick={toggleMenu}
      aria-label="Toggle mobile menu"
    >
      <div className="w-6 h-6 flex flex-col justify-between">
        {[1, 2, 3].map((line) => (
          <motion.span
            key={line}
            custom={line}
            variants={lineVariants}
            animate={isOpen ? "open" : "closed"}
            transition={{ duration: 0.3 }}
            className={`w-full h-0.5 ${
              isDarkMode ? "bg-white" : "bg-gray-800"
            }`}
          />
        ))}
      </div>
    </button>
  );
};

export default MobileMenuButton;
