/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import NavigationItem from "./NavigationItem";

interface ResponsiveMenuProps {
  isOpen: boolean;
  navigationItems: Array<{
    label: string;
    href: string;
    hasDropdown?: boolean;
  }>;
  isDarkMode: boolean;
}

const ResponsiveMenu: React.FC<ResponsiveMenuProps> = ({
  isOpen,
  navigationItems,
  isDarkMode,
}) => {
  const menuVariants = {
    open: { opacity: 1, height: "auto" },
    closed: { opacity: 0, height: 0 },
  };

  return (
    <motion.div
      initial="closed"
      animate={isOpen ? "open" : "closed"}
      variants={menuVariants}
      transition={{ duration: 0.3 }}
      className={`md:hidden overflow-hidden ${
        isDarkMode ? "bg-gray-800" : "bg-white"
      }`}
    >
      <ul className="flex flex-col items-center py-4">
        {navigationItems.map((item, index) => (
          <li key={index} className="mb-4 last:mb-0">
            <NavigationItem {...item} isDarkMode={isDarkMode} />
          </li>
        ))}
      </ul>
    </motion.div>
  );
};

export default ResponsiveMenu;
