/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import {
  FaMobileAlt,
  FaDesktop,
  FaCloud,
  FaDatabase,
  FaRobot,
  FaLock,
  FaChartBar,
  FaCog,
} from "react-icons/fa";

interface ServiceItemProps {
  name: string;
  icon: React.ElementType;
  isDarkMode: boolean;
}

const ServiceItem: React.FC<ServiceItemProps> = ({
  name,
  icon: Icon,
  isDarkMode,
}) => (
  <motion.li
    initial={{ opacity: 0, x: -10 }}
    animate={{ opacity: 1, x: 0 }}
    exit={{ opacity: 0, x: -10 }}
    className={`mb-2 last:mb-0 ${
      isDarkMode ? "text-gray-300" : "text-gray-700"
    }`}
  >
    <a
      href="#"
      className={`flex items-center p-2 rounded-md transition-colors duration-300 ${
        isDarkMode ? "hover:bg-gray-700" : "hover:bg-gray-100"
      }`}
    >
      <Icon
        className={`mr-3 ${isDarkMode ? "text-indigo-400" : "text-indigo-600"}`}
      />
      <span>{name}</span>
    </a>
  </motion.li>
);

interface ServicesDropdownProps {
  isDarkMode: boolean;
}

const ServicesDropdown: React.FC<ServicesDropdownProps> = ({ isDarkMode }) => {
  const services = [
    { name: "Mobile App Development", icon: FaMobileAlt },
    { name: "Web Development", icon: FaDesktop },
    { name: "Cloud Services", icon: FaCloud },
    { name: "Database Management", icon: FaDatabase },
    { name: "AI & Machine Learning", icon: FaRobot },
    { name: "Cybersecurity", icon: FaLock },
    { name: "Data Analytics", icon: FaChartBar },
    { name: "DevOps", icon: FaCog },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className={`absolute left-0 mt-2 w-64 rounded-md shadow-lg ${
        isDarkMode ? "bg-gray-800" : "bg-white"
      } ring-1 ring-black ring-opacity-5 focus:outline-none`}
    >
      <div className="py-1">
        <ul>
          {services.map((service, index) => (
            <ServiceItem key={index} {...service} isDarkMode={isDarkMode} />
          ))}
        </ul>
      </div>
    </motion.div>
  );
};

export default ServicesDropdown;
