/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

interface ThemeToggleProps {
  isDarkMode: boolean;
  toggleTheme: () => void;
}

const ThemeToggle: React.FC<ThemeToggleProps> = ({
  isDarkMode,
  toggleTheme,
}) => {
  return (
    <button
      onClick={toggleTheme}
      className={`relative w-14 h-8 rounded-full p-1 transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-offset-2 ${
        isDarkMode
          ? "bg-indigo-600 focus:ring-indigo-500"
          : "bg-gray-200 focus:ring-indigo-500"
      }`}
    >
      <motion.div
        className={`w-6 h-6 rounded-full shadow-md transform transition-transform duration-300 ${
          isDarkMode ? "bg-white" : "bg-indigo-500"
        }`}
        initial={false}
        animate={{ x: isDarkMode ? 24 : 0 }}
      />
    </button>
  );
};

export default ThemeToggle;
