/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HandbookItemProps {
  icon: string;
  title: string;
  description: string;
}

const HandbookItem: React.FC<HandbookItemProps> = ({
  icon,
  title,
  description,
}) => (
  <div className="flex flex-col grow shrink pb-6 bg-blend-normal min-h-[119px] min-w-[240px] w-[326px] max-md:pb-24">
    <div className="flex gap-3 max-w-full text-xl font-semibold leading-none text-white rounded-2xl w-[188px]">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 w-12 rounded-2xl bg-blend-normal aspect-square"
      />
      <div className="grow shrink my-auto w-[118px]">{title}</div>
    </div>
    <p className="flex flex-col pr-10 pb-6 mt-3 max-w-full text-lg leading-loose bg-blend-normal h-[59px] text-slate-300 w-[405px] max-md:pr-5 max-md:pb-24">
      {description}
    </p>
  </div>
);

const Handbook: React.FC = () => {
  const handbookItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2fac1255ca766e8ebe62f79da30f9e734c1cac2409d6960a38d913578e2a00f6?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e",
      title: "User focused",
      description:
        "User experience is paramount. We build for impact, intuitiveness, and joy.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a1218662506c51fae09950e6564e05d0b610812890c398b0b3b4c5d46bb48535?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e",
      title: "Clear communication",
      description:
        "Clarity guides our interactions. We ensure you're informed and involved.",
    },
  ];

  return (
    <section className="flex flex-wrap gap-10 items-start mt-32 max-w-full bg-blend-normal min-h-[560px] w-[1280px] max-md:mt-10">
      <div className="flex overflow-hidden flex-col grow shrink rounded-3xl shadow-sm bg-blend-normal bg-white bg-opacity-0 min-w-[240px] w-[298px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/faa30a1e345f4ae921f9ce594cd1430e0fa11428339475de86455804d7d21c19?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e"
          alt="Team collaboration"
          className="object-contain w-full rounded-3xl bg-blend-normal aspect-[0.67]"
        />
      </div>
      <div className="flex flex-col grow shrink bg-blend-normal min-w-[240px] w-[752px] max-md:max-w-full">
        <span className="self-start px-6 py-2 text-sm font-medium tracking-wide leading-none text-white bg-blend-normal rounded-[9999px_9999px_9999px_0px] max-md:px-5">
          Our handbook
        </span>
        <h2 className="flex flex-col pr-4 pb-5 mt-6 text-5xl font-extrabold leading-none text-white bg-blend-normal min-h-[96px] max-md:pb-24 max-md:max-w-full max-md:text-4xl">
          How we work and collaborate with our clients
        </h2>
        <p className="flex flex-col pr-8 pb-6 mt-6 text-xl leading-none bg-blend-normal min-h-[84px] text-slate-300 max-md:pr-5 max-md:pb-24 max-md:max-w-full">
          Our work philosophy revolves around active collaboration and open
          dialogue. We engage with clients every step of the way, ensuring their
          vision is at the heart of our designs and strategies.
        </p>
        <div className="flex flex-wrap gap-6 items-start mt-10 bg-blend-normal min-h-[119px]">
          {handbookItems.map((item, index) => (
            <HandbookItem key={index} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Handbook;
