/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero: React.FC = () => {
  return (
    <section className="flex flex-col items-center py-8 sm:py-12 md:py-16 w-full">
      <div className="flex flex-col px-4 sm:px-8 md:px-16 lg:px-32 w-full max-w-screen-xl bg-blend-normal">
        <div className="flex flex-col items-center px-4 sm:px-6 md:px-10 w-full text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-extrabold leading-tight sm:leading-none text-white bg-blend-normal">

          <h1 className="self-stretch mt-4 sm:mt-5 text-center">
            A small creative team excited to create beautiful things
          </h1>
          <p className="mt-4 sm:mt-5 text-base sm:text-lg md:text-xl leading-snug sm:leading-none text-slate-300 text-center max-w-3xl">
            Born out of a shared passion for design and innovation, we&apos;re a
            dedicated team committed to turning visions into impactful digital
            realities.
          </p>
        </div>
        <div className="flex overflow-hidden flex-col mt-8 sm:mt-12 w-full rounded-3xl shadow-sm bg-blend-normal bg-white bg-opacity-0">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/802a1d05071cb0795a281cb1070aecfe020f13f3e197661fc64a2ca7145cc21b?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e"
            alt="Team working together"
            className="object-cover w-full rounded-3xl bg-blend-normal aspect-[1.5]"
          />
        </div>
      </div>
    </section>
  );
};

export default Hero;
