/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ValueItemProps {
  icon: string;
  title: string;
  description: string;
}

const ValueItem: React.FC<ValueItemProps> = ({ icon, title, description }) => (
  <div className="flex overflow-hidden flex-col grow shrink items-center px-14 pt-16 pb-32 rounded-3xl shadow-sm  min-w-[240px] w-[328px] max-md:px-5 max-md:pb-24">
    <img loading="lazy" src={icon} alt="" className="object-contain rounded-3xl bg-blend-normal aspect-square shadow-[0px_0px_0px_rgba(0,0,0,0)] w-[72px]" />
    <h3 className="mt-8 text-2xl font-bold leading-none text-white">{title}</h3>
    <p className="self-stretch mt-3.5 text-lg leading-loose text-slate-300">{description}</p>
  </div>
);

const Values: React.FC = () => {
  const valueItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/516aa68cb5f0132c36b5c48af6a4798d811b523209043ab033e3b9d5fbc51491?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e",
      title: "Quality",
      description: "We strive for excellence in all facets"
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e470414fb9164781dca3ebcff3fdc8782ced02d31d8aaf0c6bed7e1db14fc3af?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e",
      title: "Improvement",
      description: "adapting, and constantly elevating"
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8c7cfb7ae250ad146a5c41a93afc0bac47922a0248d62c77b202b40aea8c0eb8?placeholderIfAbsent=true&apiKey=f728a3c9ac5f453984800130362dac4e",
      title: "Team work",
      description: "fostering a culture of collaboration"
    }
  ];

  return (
    <section className="flex flex-col items-center mt-32 max-md:mt-10">
      <span className="px-6 py-2 mt-12 max-w-full text-sm font-medium tracking-wide leading-none text-white bg-blend-normal rounded-[9999px_9999px_9999px_0px] w-[123px] max-md:px-5 max-md:mt-10">Our values</span>
      <h2 className="mt-6 text-5xl font-extrabold leading-none text-white max-md:max-w-full max-md:text-4xl">
        The values that guide and define our work
      </h2>
      <p className="mt-6 text-xl leading-none text-slate-300 max-md:max-w-full">
        We are driven by a unique ethos, firmly rooted in a cohesive set of shared values that guide all our decisions and actions.
      </p>
      <div className="flex flex-wrap gap-6 items-start mt-16 w-full max-w-screen-xl bg-blend-normal min-h-[364px] max-md:mt-10 max-md:max-w-full">
        {valueItems.map((item, index) => (
          <ValueItem key={index} {...item} />
        ))}
      </div>
    </section>
  );
};

export default Values;